# ArionComply Demo - pubspec.yaml
# Revolutionary "Personal AI Expert" Platform Demo
# Focus: Avatar-first interface with multi-modal conversation

name: arioncomply_demo
description: ArionComply Personal AI Compliance Expert Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management - Riverpod for complex business logic
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing - GoRouter for web-friendly routing  
  go_router: ^13.0.0

  # UI & Animations - For avatar interface
  animations: ^2.0.11
  lottie: ^3.0.0
  rive: ^0.12.4

  # Speech & Audio - Multi-modal conversation system
  speech_to_text: ^6.6.0
  text_to_speech: ^4.0.2
  flutter_tts: ^4.0.2
  record: ^5.0.4
  audioplayers: ^5.2.1

  # HTTP & API - For AI backend integration
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Storage - Local persistence for demo data
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils & Helpers
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.2

  # Web-specific for embedding
  js: ^0.6.7
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    # Avatar Assets
    - assets/avatars/
    - assets/animations/
    - assets/audio/
    
    # Framework Data
    - assets/data/frameworks.json
    - assets/data/questions.json
    - assets/data/templates.json
    
    # Images & Icons
    - assets/images/
    - assets/icons/
    
    # Fonts for professional appearance
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700